---
title: "FlexShiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
imdb <- read_rds("../dados/imdb.rds")
```

Column {.sidebar}
-----------------------------------------------------------------------

Você pode colocar todos os inputs aqui.

```{r}
selectInput(
  inputId = "variavel",
  label = "Selecione a variável",
  choices = c(
    "Orçamento" = "orcamento", 
    "Receita" = "receita", 
    "Lucro" = "lucro"
  )
)
```

Column
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlot({
  imdb %>% 
    mutate(lucro = receita - orcamento) %>% 
    pivot_longer(cols = one_of(c("orcamento", "receita", "lucro"))) %>% 
    filter(name == input$variavel) %>% 
    group_by(ano) %>% 
    summarise(valor_medio = mean(value, na.rm = TRUE)) %>% 
    filter(!is.na(valor_medio)) %>% 
    ggplot(aes(x = ano, y = valor_medio)) +
    geom_line() +
    labs(y = input$variavel) +
    theme_minimal()
})
```


